export const SET_CITY_NAME = "LOCATION/SET_CITY_NAME";
export const SET_CITY_ADDRESS = "LOCATION/SET_CITY_ADDRESS";
export const FETCH_CITIES = "LOCATION/FETCH_CITIES";
export const FETCH_POINTS = "LOCATION/FETCH_POINTS";
export const FETCH_CARS = "MODEL/FETCH_CARS";
export const SET_MODEL = "MODEL/SET_MODEL";
