export const SET_CITY_NAME = "LOCATION/SET_CITY_NAME";
export const SET_CITY_ADDRESS = "LOCATION/SET_CITY_ADDRESS";
export const FETCH_CITIES = "LOCATION/LOAD_CITIES";
export const FETCH_POINTS = "LOCATION/LOAD_POINTS";
export const LOAD_CARS = "MODEL/LOAD_CARS";
